graph LR
cert-manager_cert-manager["{cert-manager_cert-manager cert-manager Deployment cert-manager}"] -->|owns| cert-manager_cert-manager-74b56b6655["{cert-manager_cert-manager-74b56b6655 cert-manager-74b56b6655 ReplicaSet cert-manager}"]
cert-manager_cert-manager-74b56b6655["{cert-manager_cert-manager-74b56b6655 cert-manager-74b56b6655 ReplicaSet cert-manager}"] -->|owns| cert-manager_cert-manager-74b56b6655-5jfsc["{cert-manager_cert-manager-74b56b6655-5jfsc cert-manager-74b56b6655-5jfsc Pod cert-manager}"]
cert-manager_cert-manager-cainjector["{cert-manager_cert-manager-cainjector cert-manager-cainjector Deployment cert-manager}"] -->|owns| cert-manager_cert-manager-cainjector-55d94dc4cc["{cert-manager_cert-manager-cainjector-55d94dc4cc cert-manager-cainjector-55d94dc4cc ReplicaSet cert-manager}"]
cert-manager_cert-manager-cainjector-55d94dc4cc["{cert-manager_cert-manager-cainjector-55d94dc4cc cert-manager-cainjector-55d94dc4cc ReplicaSet cert-manager}"] -->|owns| cert-manager_cert-manager-cainjector-55d94dc4cc-85kjv["{cert-manager_cert-manager-cainjector-55d94dc4cc-85kjv cert-manager-cainjector-55d94dc4cc-85kjv Pod cert-manager}"]
cert-manager_cert-manager-webhook["{cert-manager_cert-manager-webhook cert-manager-webhook Deployment cert-manager}"] -->|owns| cert-manager_cert-manager-webhook-564f647c66["{cert-manager_cert-manager-webhook-564f647c66 cert-manager-webhook-564f647c66 ReplicaSet cert-manager}"]
cert-manager_cert-manager-webhook-564f647c66["{cert-manager_cert-manager-webhook-564f647c66 cert-manager-webhook-564f647c66 ReplicaSet cert-manager}"] -->|owns| cert-manager_cert-manager-webhook-564f647c66-8b55j["{cert-manager_cert-manager-webhook-564f647c66-8b55j cert-manager-webhook-564f647c66-8b55j Pod cert-manager}"]
kube-system_coredns["{kube-system_coredns coredns Deployment kube-system}"] -->|owns| kube-system_coredns-5ddb6c7994["{kube-system_coredns-5ddb6c7994 coredns-5ddb6c7994 ReplicaSet kube-system}"]
kube-system_coredns-5ddb6c7994["{kube-system_coredns-5ddb6c7994 coredns-5ddb6c7994 ReplicaSet kube-system}"] -->|owns| kube-system_coredns-5ddb6c7994-26w5v["{kube-system_coredns-5ddb6c7994-26w5v coredns-5ddb6c7994-26w5v Pod kube-system}"]
kube-system_coredns-5ddb6c7994["{kube-system_coredns-5ddb6c7994 coredns-5ddb6c7994 ReplicaSet kube-system}"] -->|owns| kube-system_coredns-5ddb6c7994-2sd55["{kube-system_coredns-5ddb6c7994-2sd55 coredns-5ddb6c7994-2sd55 Pod kube-system}"]
kube-system_coredns["{kube-system_coredns coredns Deployment kube-system}"] -->|owns| kube-system_coredns-c4dd86697["{kube-system_coredns-c4dd86697 coredns-c4dd86697 ReplicaSet kube-system}"]
kube-system_kube-ovn-controller["{kube-system_kube-ovn-controller kube-ovn-controller Deployment kube-system}"] -->|owns| kube-system_kube-ovn-controller-56ffd466d6["{kube-system_kube-ovn-controller-56ffd466d6 kube-ovn-controller-56ffd466d6 ReplicaSet kube-system}"]
kube-system_kube-ovn-controller-56ffd466d6["{kube-system_kube-ovn-controller-56ffd466d6 kube-ovn-controller-56ffd466d6 ReplicaSet kube-system}"] -->|owns| kube-system_kube-ovn-controller-56ffd466d6-m6l4w["{kube-system_kube-ovn-controller-56ffd466d6-m6l4w kube-ovn-controller-56ffd466d6-m6l4w Pod kube-system}"]
kube-system_kube-ovn-monitor["{kube-system_kube-ovn-monitor kube-ovn-monitor Deployment kube-system}"] -->|owns| kube-system_kube-ovn-monitor-7b75cf6675["{kube-system_kube-ovn-monitor-7b75cf6675 kube-ovn-monitor-7b75cf6675 ReplicaSet kube-system}"]
kube-system_kube-ovn-monitor-7b75cf6675["{kube-system_kube-ovn-monitor-7b75cf6675 kube-ovn-monitor-7b75cf6675 ReplicaSet kube-system}"] -->|owns| kube-system_kube-ovn-monitor-7b75cf6675-qt8tc["{kube-system_kube-ovn-monitor-7b75cf6675-qt8tc kube-ovn-monitor-7b75cf6675-qt8tc Pod kube-system}"]
kube-system_ovn-central["{kube-system_ovn-central ovn-central Deployment kube-system}"] -->|owns| kube-system_ovn-central-6989cd88bd["{kube-system_ovn-central-6989cd88bd ovn-central-6989cd88bd ReplicaSet kube-system}"]
kube-system_ovn-central-6989cd88bd["{kube-system_ovn-central-6989cd88bd ovn-central-6989cd88bd ReplicaSet kube-system}"] -->|owns| kube-system_ovn-central-6989cd88bd-fkn8w["{kube-system_ovn-central-6989cd88bd-fkn8w ovn-central-6989cd88bd-fkn8w Pod kube-system}"]
kubesphere-system_extensions-museum["{kubesphere-system_extensions-museum extensions-museum Deployment kubesphere-system}"] -->|owns| kubesphere-system_extensions-museum-b5f957cc9["{kubesphere-system_extensions-museum-b5f957cc9 extensions-museum-b5f957cc9 ReplicaSet kubesphere-system}"]
kubesphere-system_extensions-museum-b5f957cc9["{kubesphere-system_extensions-museum-b5f957cc9 extensions-museum-b5f957cc9 ReplicaSet kubesphere-system}"] -->|owns| kubesphere-system_extensions-museum-b5f957cc9-wm9nk["{kubesphere-system_extensions-museum-b5f957cc9-wm9nk extensions-museum-b5f957cc9-wm9nk Pod kubesphere-system}"]
kubesphere-system_ks-apiserver["{kubesphere-system_ks-apiserver ks-apiserver Deployment kubesphere-system}"] -->|owns| kubesphere-system_ks-apiserver-8bc56b888["{kubesphere-system_ks-apiserver-8bc56b888 ks-apiserver-8bc56b888 ReplicaSet kubesphere-system}"]
kubesphere-system_ks-apiserver-8bc56b888["{kubesphere-system_ks-apiserver-8bc56b888 ks-apiserver-8bc56b888 ReplicaSet kubesphere-system}"] -->|owns| kubesphere-system_ks-apiserver-8bc56b888-ng26w["{kubesphere-system_ks-apiserver-8bc56b888-ng26w ks-apiserver-8bc56b888-ng26w Pod kubesphere-system}"]
kubesphere-system_ks-console["{kubesphere-system_ks-console ks-console Deployment kubesphere-system}"] -->|owns| kubesphere-system_ks-console-644d4d4d4d["{kubesphere-system_ks-console-644d4d4d4d ks-console-644d4d4d4d ReplicaSet kubesphere-system}"]
kubesphere-system_ks-console-644d4d4d4d["{kubesphere-system_ks-console-644d4d4d4d ks-console-644d4d4d4d ReplicaSet kubesphere-system}"] -->|owns| kubesphere-system_ks-console-644d4d4d4d-t9qcq["{kubesphere-system_ks-console-644d4d4d4d-t9qcq ks-console-644d4d4d4d-t9qcq Pod kubesphere-system}"]
kubesphere-system_ks-console["{kubesphere-system_ks-console ks-console Deployment kubesphere-system}"] -->|owns| kubesphere-system_ks-console-659df455f9["{kubesphere-system_ks-console-659df455f9 ks-console-659df455f9 ReplicaSet kubesphere-system}"]
kubesphere-system_ks-console["{kubesphere-system_ks-console ks-console Deployment kubesphere-system}"] -->|owns| kubesphere-system_ks-console-7c499d44f5["{kubesphere-system_ks-console-7c499d44f5 ks-console-7c499d44f5 ReplicaSet kubesphere-system}"]
kubesphere-system_ks-console["{kubesphere-system_ks-console ks-console Deployment kubesphere-system}"] -->|owns| kubesphere-system_ks-console-7d7b496cbf["{kubesphere-system_ks-console-7d7b496cbf ks-console-7d7b496cbf ReplicaSet kubesphere-system}"]
kubesphere-system_ks-controller-manager["{kubesphere-system_ks-controller-manager ks-controller-manager Deployment kubesphere-system}"] -->|owns| kubesphere-system_ks-controller-manager-5cdd475c84["{kubesphere-system_ks-controller-manager-5cdd475c84 ks-controller-manager-5cdd475c84 ReplicaSet kubesphere-system}"]
kubesphere-system_ks-controller-manager-5cdd475c84["{kubesphere-system_ks-controller-manager-5cdd475c84 ks-controller-manager-5cdd475c84 ReplicaSet kubesphere-system}"] -->|owns| kubesphere-system_ks-controller-manager-5cdd475c84-kf9qn["{kubesphere-system_ks-controller-manager-5cdd475c84-kf9qn ks-controller-manager-5cdd475c84-kf9qn Pod kubesphere-system}"]
logging-tracing_jaeger["{logging-tracing_jaeger jaeger Deployment logging-tracing}"] -->|owns| logging-tracing_jaeger-58d497df44["{logging-tracing_jaeger-58d497df44 jaeger-58d497df44 ReplicaSet logging-tracing}"]
logging-tracing_jaeger-58d497df44["{logging-tracing_jaeger-58d497df44 jaeger-58d497df44 ReplicaSet logging-tracing}"] -->|owns| logging-tracing_jaeger-58d497df44-6zt8q["{logging-tracing_jaeger-58d497df44-6zt8q jaeger-58d497df44-6zt8q Pod logging-tracing}"]
mariadb-system_mariadb-operator["{mariadb-system_mariadb-operator mariadb-operator Deployment mariadb-system}"] -->|owns| mariadb-system_mariadb-operator-7546d67f9c["{mariadb-system_mariadb-operator-7546d67f9c mariadb-operator-7546d67f9c ReplicaSet mariadb-system}"]
mariadb-system_mariadb-operator-7546d67f9c["{mariadb-system_mariadb-operator-7546d67f9c mariadb-operator-7546d67f9c ReplicaSet mariadb-system}"] -->|owns| mariadb-system_mariadb-operator-7546d67f9c-k2zbg["{mariadb-system_mariadb-operator-7546d67f9c-k2zbg mariadb-operator-7546d67f9c-k2zbg Pod mariadb-system}"]
mariadb-system_mariadb-operator-webhook["{mariadb-system_mariadb-operator-webhook mariadb-operator-webhook Deployment mariadb-system}"] -->|owns| mariadb-system_mariadb-operator-webhook-7786978598["{mariadb-system_mariadb-operator-webhook-7786978598 mariadb-operator-webhook-7786978598 ReplicaSet mariadb-system}"]
mariadb-system_mariadb-operator-webhook-7786978598["{mariadb-system_mariadb-operator-webhook-7786978598 mariadb-operator-webhook-7786978598 ReplicaSet mariadb-system}"] -->|owns| mariadb-system_mariadb-operator-webhook-7786978598-tf24q["{mariadb-system_mariadb-operator-webhook-7786978598-tf24q mariadb-operator-webhook-7786978598-tf24q Pod mariadb-system}"]
metallb-system_metallb-controller["{metallb-system_metallb-controller metallb-controller Deployment metallb-system}"] -->|owns| metallb-system_metallb-controller-777b99b66c["{metallb-system_metallb-controller-777b99b66c metallb-controller-777b99b66c ReplicaSet metallb-system}"]
metallb-system_metallb-controller-777b99b66c["{metallb-system_metallb-controller-777b99b66c metallb-controller-777b99b66c ReplicaSet metallb-system}"] -->|owns| metallb-system_metallb-controller-777b99b66c-kshg7["{metallb-system_metallb-controller-777b99b66c-kshg7 metallb-controller-777b99b66c-kshg7 Pod metallb-system}"]
nginx-gateway_nginx-gateway-fabric["{nginx-gateway_nginx-gateway-fabric nginx-gateway-fabric Deployment nginx-gateway}"] -->|owns| nginx-gateway_nginx-gateway-fabric-6b474b7869["{nginx-gateway_nginx-gateway-fabric-6b474b7869 nginx-gateway-fabric-6b474b7869 ReplicaSet nginx-gateway}"]
nginx-gateway_nginx-gateway-fabric-6b474b7869["{nginx-gateway_nginx-gateway-fabric-6b474b7869 nginx-gateway-fabric-6b474b7869 ReplicaSet nginx-gateway}"] -->|owns| nginx-gateway_nginx-gateway-fabric-6b474b7869-vnfkj["{nginx-gateway_nginx-gateway-fabric-6b474b7869-vnfkj nginx-gateway-fabric-6b474b7869-vnfkj Pod nginx-gateway}"]
openstack_barbican-api["{openstack_barbican-api barbican-api Deployment openstack}"] -->|owns| openstack_barbican-api-57654c74f6["{openstack_barbican-api-57654c74f6 barbican-api-57654c74f6 ReplicaSet openstack}"]
openstack_barbican-api-57654c74f6["{openstack_barbican-api-57654c74f6 barbican-api-57654c74f6 ReplicaSet openstack}"] -->|owns| openstack_barbican-api-57654c74f6-9d5nh["{openstack_barbican-api-57654c74f6-9d5nh barbican-api-57654c74f6-9d5nh Pod openstack}"]
openstack_ceilometer-central["{openstack_ceilometer-central ceilometer-central Deployment openstack}"] -->|owns| openstack_ceilometer-central-697cd74cb5["{openstack_ceilometer-central-697cd74cb5 ceilometer-central-697cd74cb5 ReplicaSet openstack}"]
openstack_ceilometer-central-697cd74cb5["{openstack_ceilometer-central-697cd74cb5 ceilometer-central-697cd74cb5 ReplicaSet openstack}"] -->|owns| openstack_ceilometer-central-697cd74cb5-qnqnq["{openstack_ceilometer-central-697cd74cb5-qnqnq ceilometer-central-697cd74cb5-qnqnq Pod openstack}"]
openstack_ceilometer-notification["{openstack_ceilometer-notification ceilometer-notification Deployment openstack}"] -->|owns| openstack_ceilometer-notification-6dfd4d99cd["{openstack_ceilometer-notification-6dfd4d99cd ceilometer-notification-6dfd4d99cd ReplicaSet openstack}"]
openstack_ceilometer-notification-6dfd4d99cd["{openstack_ceilometer-notification-6dfd4d99cd ceilometer-notification-6dfd4d99cd ReplicaSet openstack}"] -->|owns| openstack_ceilometer-notification-6dfd4d99cd-xcgf7["{openstack_ceilometer-notification-6dfd4d99cd-xcgf7 ceilometer-notification-6dfd4d99cd-xcgf7 Pod openstack}"]
openstack_cinder-api["{openstack_cinder-api cinder-api Deployment openstack}"] -->|owns| openstack_cinder-api-8b8b9965b["{openstack_cinder-api-8b8b9965b cinder-api-8b8b9965b ReplicaSet openstack}"]
openstack_cinder-api-8b8b9965b["{openstack_cinder-api-8b8b9965b cinder-api-8b8b9965b ReplicaSet openstack}"] -->|owns| openstack_cinder-api-8b8b9965b-6d952["{openstack_cinder-api-8b8b9965b-6d952 cinder-api-8b8b9965b-6d952 Pod openstack}"]
openstack_cinder-scheduler["{openstack_cinder-scheduler cinder-scheduler Deployment openstack}"] -->|owns| openstack_cinder-scheduler-6796cb458c["{openstack_cinder-scheduler-6796cb458c cinder-scheduler-6796cb458c ReplicaSet openstack}"]
openstack_cinder-scheduler-6796cb458c["{openstack_cinder-scheduler-6796cb458c cinder-scheduler-6796cb458c ReplicaSet openstack}"] -->|owns| openstack_cinder-scheduler-6796cb458c-pxv7p["{openstack_cinder-scheduler-6796cb458c-pxv7p cinder-scheduler-6796cb458c-pxv7p Pod openstack}"]
openstack_cinder-volume["{openstack_cinder-volume cinder-volume Deployment openstack}"] -->|owns| openstack_cinder-volume-858df5d96["{openstack_cinder-volume-858df5d96 cinder-volume-858df5d96 ReplicaSet openstack}"]
openstack_cinder-volume-858df5d96["{openstack_cinder-volume-858df5d96 cinder-volume-858df5d96 ReplicaSet openstack}"] -->|owns| openstack_cinder-volume-858df5d96-pwg8h["{openstack_cinder-volume-858df5d96-pwg8h cinder-volume-858df5d96-pwg8h Pod openstack}"]
openstack_glance-api["{openstack_glance-api glance-api Deployment openstack}"] -->|owns| openstack_glance-api-548876b7f8["{openstack_glance-api-548876b7f8 glance-api-548876b7f8 ReplicaSet openstack}"]
openstack_glance-api-548876b7f8["{openstack_glance-api-548876b7f8 glance-api-548876b7f8 ReplicaSet openstack}"] -->|owns| openstack_glance-api-548876b7f8-hjg4c["{openstack_glance-api-548876b7f8-hjg4c glance-api-548876b7f8-hjg4c Pod openstack}"]
openstack_heat-api["{openstack_heat-api heat-api Deployment openstack}"] -->|owns| openstack_heat-api-588b946fd5["{openstack_heat-api-588b946fd5 heat-api-588b946fd5 ReplicaSet openstack}"]
openstack_heat-api-588b946fd5["{openstack_heat-api-588b946fd5 heat-api-588b946fd5 ReplicaSet openstack}"] -->|owns| openstack_heat-api-588b946fd5-854b4["{openstack_heat-api-588b946fd5-854b4 heat-api-588b946fd5-854b4 Pod openstack}"]
openstack_heat-cfn["{openstack_heat-cfn heat-cfn Deployment openstack}"] -->|owns| openstack_heat-cfn-7b8cb9bc45["{openstack_heat-cfn-7b8cb9bc45 heat-cfn-7b8cb9bc45 ReplicaSet openstack}"]
openstack_heat-cfn-7b8cb9bc45["{openstack_heat-cfn-7b8cb9bc45 heat-cfn-7b8cb9bc45 ReplicaSet openstack}"] -->|owns| openstack_heat-cfn-7b8cb9bc45-54c8n["{openstack_heat-cfn-7b8cb9bc45-54c8n heat-cfn-7b8cb9bc45-54c8n Pod openstack}"]
openstack_heat-engine["{openstack_heat-engine heat-engine Deployment openstack}"] -->|owns| openstack_heat-engine-559f48d65["{openstack_heat-engine-559f48d65 heat-engine-559f48d65 ReplicaSet openstack}"]
openstack_heat-engine-559f48d65["{openstack_heat-engine-559f48d65 heat-engine-559f48d65 ReplicaSet openstack}"] -->|owns| openstack_heat-engine-559f48d65-mgk2n["{openstack_heat-engine-559f48d65-mgk2n heat-engine-559f48d65-mgk2n Pod openstack}"]
openstack_horizon["{openstack_horizon horizon Deployment openstack}"] -->|owns| openstack_horizon-74f9bcf99c["{openstack_horizon-74f9bcf99c horizon-74f9bcf99c ReplicaSet openstack}"]
openstack_horizon-74f9bcf99c["{openstack_horizon-74f9bcf99c horizon-74f9bcf99c ReplicaSet openstack}"] -->|owns| openstack_horizon-74f9bcf99c-8c4n9["{openstack_horizon-74f9bcf99c-8c4n9 horizon-74f9bcf99c-8c4n9 Pod openstack}"]
openstack_keystone-api["{openstack_keystone-api keystone-api Deployment openstack}"] -->|owns| openstack_keystone-api-848d97fcb7["{openstack_keystone-api-848d97fcb7 keystone-api-848d97fcb7 ReplicaSet openstack}"]
openstack_keystone-api-848d97fcb7["{openstack_keystone-api-848d97fcb7 keystone-api-848d97fcb7 ReplicaSet openstack}"] -->|owns| openstack_keystone-api-848d97fcb7-xn9kx["{openstack_keystone-api-848d97fcb7-xn9kx keystone-api-848d97fcb7-xn9kx Pod openstack}"]
openstack_neutron-rpc-server["{openstack_neutron-rpc-server neutron-rpc-server Deployment openstack}"] -->|owns| openstack_neutron-rpc-server-597d8d8bfd["{openstack_neutron-rpc-server-597d8d8bfd neutron-rpc-server-597d8d8bfd ReplicaSet openstack}"]
openstack_neutron-rpc-server["{openstack_neutron-rpc-server neutron-rpc-server Deployment openstack}"] -->|owns| openstack_neutron-rpc-server-6b495f596c["{openstack_neutron-rpc-server-6b495f596c neutron-rpc-server-6b495f596c ReplicaSet openstack}"]
openstack_neutron-rpc-server-6b495f596c["{openstack_neutron-rpc-server-6b495f596c neutron-rpc-server-6b495f596c ReplicaSet openstack}"] -->|owns| openstack_neutron-rpc-server-6b495f596c-6cxdp["{openstack_neutron-rpc-server-6b495f596c-6cxdp neutron-rpc-server-6b495f596c-6cxdp Pod openstack}"]
openstack_neutron-server["{openstack_neutron-server neutron-server Deployment openstack}"] -->|owns| openstack_neutron-server-55f6864dc9["{openstack_neutron-server-55f6864dc9 neutron-server-55f6864dc9 ReplicaSet openstack}"]
openstack_neutron-server-55f6864dc9["{openstack_neutron-server-55f6864dc9 neutron-server-55f6864dc9 ReplicaSet openstack}"] -->|owns| openstack_neutron-server-55f6864dc9-vv876["{openstack_neutron-server-55f6864dc9-vv876 neutron-server-55f6864dc9-vv876 Pod openstack}"]
openstack_neutron-server["{openstack_neutron-server neutron-server Deployment openstack}"] -->|owns| openstack_neutron-server-765dd99c76["{openstack_neutron-server-765dd99c76 neutron-server-765dd99c76 ReplicaSet openstack}"]
openstack_nova-api-metadata["{openstack_nova-api-metadata nova-api-metadata Deployment openstack}"] -->|owns| openstack_nova-api-metadata-6888d4599b["{openstack_nova-api-metadata-6888d4599b nova-api-metadata-6888d4599b ReplicaSet openstack}"]
openstack_nova-api-metadata["{openstack_nova-api-metadata nova-api-metadata Deployment openstack}"] -->|owns| openstack_nova-api-metadata-68f949b4bb["{openstack_nova-api-metadata-68f949b4bb nova-api-metadata-68f949b4bb ReplicaSet openstack}"]
openstack_nova-api-metadata["{openstack_nova-api-metadata nova-api-metadata Deployment openstack}"] -->|owns| openstack_nova-api-metadata-6bb4cc69cc["{openstack_nova-api-metadata-6bb4cc69cc nova-api-metadata-6bb4cc69cc ReplicaSet openstack}"]
openstack_nova-api-metadata["{openstack_nova-api-metadata nova-api-metadata Deployment openstack}"] -->|owns| openstack_nova-api-metadata-b5bdffb95["{openstack_nova-api-metadata-b5bdffb95 nova-api-metadata-b5bdffb95 ReplicaSet openstack}"]
openstack_nova-api-metadata-b5bdffb95["{openstack_nova-api-metadata-b5bdffb95 nova-api-metadata-b5bdffb95 ReplicaSet openstack}"] -->|owns| openstack_nova-api-metadata-b5bdffb95-q92gm["{openstack_nova-api-metadata-b5bdffb95-q92gm nova-api-metadata-b5bdffb95-q92gm Pod openstack}"]
openstack_nova-api-osapi["{openstack_nova-api-osapi nova-api-osapi Deployment openstack}"] -->|owns| openstack_nova-api-osapi-597fddc579["{openstack_nova-api-osapi-597fddc579 nova-api-osapi-597fddc579 ReplicaSet openstack}"]
openstack_nova-api-osapi["{openstack_nova-api-osapi nova-api-osapi Deployment openstack}"] -->|owns| openstack_nova-api-osapi-6cf558756b["{openstack_nova-api-osapi-6cf558756b nova-api-osapi-6cf558756b ReplicaSet openstack}"]
openstack_nova-api-osapi-6cf558756b["{openstack_nova-api-osapi-6cf558756b nova-api-osapi-6cf558756b ReplicaSet openstack}"] -->|owns| openstack_nova-api-osapi-6cf558756b-7gfw8["{openstack_nova-api-osapi-6cf558756b-7gfw8 nova-api-osapi-6cf558756b-7gfw8 Pod openstack}"]
openstack_nova-api-osapi["{openstack_nova-api-osapi nova-api-osapi Deployment openstack}"] -->|owns| openstack_nova-api-osapi-79f5d8bf4f["{openstack_nova-api-osapi-79f5d8bf4f nova-api-osapi-79f5d8bf4f ReplicaSet openstack}"]
openstack_nova-api-osapi["{openstack_nova-api-osapi nova-api-osapi Deployment openstack}"] -->|owns| openstack_nova-api-osapi-85b97bc876["{openstack_nova-api-osapi-85b97bc876 nova-api-osapi-85b97bc876 ReplicaSet openstack}"]
openstack_nova-conductor["{openstack_nova-conductor nova-conductor Deployment openstack}"] -->|owns| openstack_nova-conductor-5bd598f77f["{openstack_nova-conductor-5bd598f77f nova-conductor-5bd598f77f ReplicaSet openstack}"]
openstack_nova-conductor["{openstack_nova-conductor nova-conductor Deployment openstack}"] -->|owns| openstack_nova-conductor-76484565cc["{openstack_nova-conductor-76484565cc nova-conductor-76484565cc ReplicaSet openstack}"]
openstack_nova-conductor["{openstack_nova-conductor nova-conductor Deployment openstack}"] -->|owns| openstack_nova-conductor-8667d98["{openstack_nova-conductor-8667d98 nova-conductor-8667d98 ReplicaSet openstack}"]
openstack_nova-conductor-8667d98["{openstack_nova-conductor-8667d98 nova-conductor-8667d98 ReplicaSet openstack}"] -->|owns| openstack_nova-conductor-8667d98-mp9gq["{openstack_nova-conductor-8667d98-mp9gq nova-conductor-8667d98-mp9gq Pod openstack}"]
openstack_nova-conductor["{openstack_nova-conductor nova-conductor Deployment openstack}"] -->|owns| openstack_nova-conductor-94d987659["{openstack_nova-conductor-94d987659 nova-conductor-94d987659 ReplicaSet openstack}"]
openstack_nova-novncproxy["{openstack_nova-novncproxy nova-novncproxy Deployment openstack}"] -->|owns| openstack_nova-novncproxy-5bfbdbc6cb["{openstack_nova-novncproxy-5bfbdbc6cb nova-novncproxy-5bfbdbc6cb ReplicaSet openstack}"]
openstack_nova-novncproxy-5bfbdbc6cb["{openstack_nova-novncproxy-5bfbdbc6cb nova-novncproxy-5bfbdbc6cb ReplicaSet openstack}"] -->|owns| openstack_nova-novncproxy-5bfbdbc6cb-n4jh8["{openstack_nova-novncproxy-5bfbdbc6cb-n4jh8 nova-novncproxy-5bfbdbc6cb-n4jh8 Pod openstack}"]
openstack_nova-novncproxy["{openstack_nova-novncproxy nova-novncproxy Deployment openstack}"] -->|owns| openstack_nova-novncproxy-64798f848f["{openstack_nova-novncproxy-64798f848f nova-novncproxy-64798f848f ReplicaSet openstack}"]
openstack_nova-novncproxy["{openstack_nova-novncproxy nova-novncproxy Deployment openstack}"] -->|owns| openstack_nova-novncproxy-855d4f9777["{openstack_nova-novncproxy-855d4f9777 nova-novncproxy-855d4f9777 ReplicaSet openstack}"]
openstack_nova-novncproxy["{openstack_nova-novncproxy nova-novncproxy Deployment openstack}"] -->|owns| openstack_nova-novncproxy-f7b8cbb4c["{openstack_nova-novncproxy-f7b8cbb4c nova-novncproxy-f7b8cbb4c ReplicaSet openstack}"]
openstack_nova-scheduler["{openstack_nova-scheduler nova-scheduler Deployment openstack}"] -->|owns| openstack_nova-scheduler-6d4dbb9447["{openstack_nova-scheduler-6d4dbb9447 nova-scheduler-6d4dbb9447 ReplicaSet openstack}"]
openstack_nova-scheduler["{openstack_nova-scheduler nova-scheduler Deployment openstack}"] -->|owns| openstack_nova-scheduler-6d77c66bcf["{openstack_nova-scheduler-6d77c66bcf nova-scheduler-6d77c66bcf ReplicaSet openstack}"]
openstack_nova-scheduler["{openstack_nova-scheduler nova-scheduler Deployment openstack}"] -->|owns| openstack_nova-scheduler-7b56656b49["{openstack_nova-scheduler-7b56656b49 nova-scheduler-7b56656b49 ReplicaSet openstack}"]
openstack_nova-scheduler["{openstack_nova-scheduler nova-scheduler Deployment openstack}"] -->|owns| openstack_nova-scheduler-fbf99c458["{openstack_nova-scheduler-fbf99c458 nova-scheduler-fbf99c458 ReplicaSet openstack}"]
openstack_nova-scheduler-fbf99c458["{openstack_nova-scheduler-fbf99c458 nova-scheduler-fbf99c458 ReplicaSet openstack}"] -->|owns| openstack_nova-scheduler-fbf99c458-tssxr["{openstack_nova-scheduler-fbf99c458-tssxr nova-scheduler-fbf99c458-tssxr Pod openstack}"]
openstack_octavia-api["{openstack_octavia-api octavia-api Deployment openstack}"] -->|owns| openstack_octavia-api-6f94c7d5df["{openstack_octavia-api-6f94c7d5df octavia-api-6f94c7d5df ReplicaSet openstack}"]
openstack_octavia-api-6f94c7d5df["{openstack_octavia-api-6f94c7d5df octavia-api-6f94c7d5df ReplicaSet openstack}"] -->|owns| openstack_octavia-api-6f94c7d5df-fdvsm["{openstack_octavia-api-6f94c7d5df-fdvsm octavia-api-6f94c7d5df-fdvsm Pod openstack}"]
openstack_octavia-housekeeping["{openstack_octavia-housekeeping octavia-housekeeping Deployment openstack}"] -->|owns| openstack_octavia-housekeeping-669f887b59["{openstack_octavia-housekeeping-669f887b59 octavia-housekeeping-669f887b59 ReplicaSet openstack}"]
openstack_octavia-housekeeping-669f887b59["{openstack_octavia-housekeeping-669f887b59 octavia-housekeeping-669f887b59 ReplicaSet openstack}"] -->|owns| openstack_octavia-housekeeping-669f887b59-6xxbs["{openstack_octavia-housekeeping-669f887b59-6xxbs octavia-housekeeping-669f887b59-6xxbs Pod openstack}"]
openstack_octavia-worker["{openstack_octavia-worker octavia-worker Deployment openstack}"] -->|owns| openstack_octavia-worker-58c89884f9["{openstack_octavia-worker-58c89884f9 octavia-worker-58c89884f9 ReplicaSet openstack}"]
openstack_octavia-worker-58c89884f9["{openstack_octavia-worker-58c89884f9 octavia-worker-58c89884f9 ReplicaSet openstack}"] -->|owns| openstack_octavia-worker-58c89884f9-dxdnr["{openstack_octavia-worker-58c89884f9-dxdnr octavia-worker-58c89884f9-dxdnr Pod openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-57c6574b9b["{openstack_otlp-opentelemetry-collector-57c6574b9b otlp-opentelemetry-collector-57c6574b9b ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-5c44887db["{openstack_otlp-opentelemetry-collector-5c44887db otlp-opentelemetry-collector-5c44887db ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-5f84bcd6d4["{openstack_otlp-opentelemetry-collector-5f84bcd6d4 otlp-opentelemetry-collector-5f84bcd6d4 ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-5f966df745["{openstack_otlp-opentelemetry-collector-5f966df745 otlp-opentelemetry-collector-5f966df745 ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-69794d7d59["{openstack_otlp-opentelemetry-collector-69794d7d59 otlp-opentelemetry-collector-69794d7d59 ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-6cd585fb78["{openstack_otlp-opentelemetry-collector-6cd585fb78 otlp-opentelemetry-collector-6cd585fb78 ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-754c7d7d4d["{openstack_otlp-opentelemetry-collector-754c7d7d4d otlp-opentelemetry-collector-754c7d7d4d ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-778b8c4674["{openstack_otlp-opentelemetry-collector-778b8c4674 otlp-opentelemetry-collector-778b8c4674 ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector["{openstack_otlp-opentelemetry-collector otlp-opentelemetry-collector Deployment openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-8497bdff99["{openstack_otlp-opentelemetry-collector-8497bdff99 otlp-opentelemetry-collector-8497bdff99 ReplicaSet openstack}"]
openstack_otlp-opentelemetry-collector-8497bdff99["{openstack_otlp-opentelemetry-collector-8497bdff99 otlp-opentelemetry-collector-8497bdff99 ReplicaSet openstack}"] -->|owns| openstack_otlp-opentelemetry-collector-8497bdff99-q9sxc["{openstack_otlp-opentelemetry-collector-8497bdff99-q9sxc otlp-opentelemetry-collector-8497bdff99-q9sxc Pod openstack}"]
openstack_placement-api["{openstack_placement-api placement-api Deployment openstack}"] -->|owns| openstack_placement-api-884f644c6["{openstack_placement-api-884f644c6 placement-api-884f644c6 ReplicaSet openstack}"]
openstack_placement-api-884f644c6["{openstack_placement-api-884f644c6 placement-api-884f644c6 ReplicaSet openstack}"] -->|owns| openstack_placement-api-884f644c6-ztj6k["{openstack_placement-api-884f644c6-ztj6k placement-api-884f644c6-ztj6k Pod openstack}"]
rabbitmq-system_messaging-topology-operator["{rabbitmq-system_messaging-topology-operator messaging-topology-operator Deployment rabbitmq-system}"] -->|owns| rabbitmq-system_messaging-topology-operator-6dfc468844["{rabbitmq-system_messaging-topology-operator-6dfc468844 messaging-topology-operator-6dfc468844 ReplicaSet rabbitmq-system}"]
rabbitmq-system_messaging-topology-operator-6dfc468844["{rabbitmq-system_messaging-topology-operator-6dfc468844 messaging-topology-operator-6dfc468844 ReplicaSet rabbitmq-system}"] -->|owns| rabbitmq-system_messaging-topology-operator-6dfc468844-cnq8v["{rabbitmq-system_messaging-topology-operator-6dfc468844-cnq8v messaging-topology-operator-6dfc468844-cnq8v Pod rabbitmq-system}"]
rabbitmq-system_rabbitmq-cluster-operator["{rabbitmq-system_rabbitmq-cluster-operator rabbitmq-cluster-operator Deployment rabbitmq-system}"] -->|owns| rabbitmq-system_rabbitmq-cluster-operator-7cb8bd8f85["{rabbitmq-system_rabbitmq-cluster-operator-7cb8bd8f85 rabbitmq-cluster-operator-7cb8bd8f85 ReplicaSet rabbitmq-system}"]
rabbitmq-system_rabbitmq-cluster-operator-7cb8bd8f85["{rabbitmq-system_rabbitmq-cluster-operator-7cb8bd8f85 rabbitmq-cluster-operator-7cb8bd8f85 ReplicaSet rabbitmq-system}"] -->|owns| rabbitmq-system_rabbitmq-cluster-operator-7cb8bd8f85-dttxx["{rabbitmq-system_rabbitmq-cluster-operator-7cb8bd8f85-dttxx rabbitmq-cluster-operator-7cb8bd8f85-dttxx Pod rabbitmq-system}"]
rook-ceph_csi-cephfsplugin-provisioner["{rook-ceph_csi-cephfsplugin-provisioner csi-cephfsplugin-provisioner Deployment rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d["{rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d csi-cephfsplugin-provisioner-cccbd7c6d ReplicaSet rook-ceph}"]
rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d["{rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d csi-cephfsplugin-provisioner-cccbd7c6d ReplicaSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d-b8xjv["{rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d-b8xjv csi-cephfsplugin-provisioner-cccbd7c6d-b8xjv Pod rook-ceph}"]
rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d["{rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d csi-cephfsplugin-provisioner-cccbd7c6d ReplicaSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d-nv5wh["{rook-ceph_csi-cephfsplugin-provisioner-cccbd7c6d-nv5wh csi-cephfsplugin-provisioner-cccbd7c6d-nv5wh Pod rook-ceph}"]
rook-ceph_csi-rbdplugin-provisioner["{rook-ceph_csi-rbdplugin-provisioner csi-rbdplugin-provisioner Deployment rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-provisioner-897c4d994["{rook-ceph_csi-rbdplugin-provisioner-897c4d994 csi-rbdplugin-provisioner-897c4d994 ReplicaSet rook-ceph}"]
rook-ceph_csi-rbdplugin-provisioner-897c4d994["{rook-ceph_csi-rbdplugin-provisioner-897c4d994 csi-rbdplugin-provisioner-897c4d994 ReplicaSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-provisioner-897c4d994-9wvqh["{rook-ceph_csi-rbdplugin-provisioner-897c4d994-9wvqh csi-rbdplugin-provisioner-897c4d994-9wvqh Pod rook-ceph}"]
rook-ceph_csi-rbdplugin-provisioner-897c4d994["{rook-ceph_csi-rbdplugin-provisioner-897c4d994 csi-rbdplugin-provisioner-897c4d994 ReplicaSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-provisioner-897c4d994-lvr48["{rook-ceph_csi-rbdplugin-provisioner-897c4d994-lvr48 csi-rbdplugin-provisioner-897c4d994-lvr48 Pod rook-ceph}"]
rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack["{rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack rook-ceph-crashcollector-ceph.cluster.openstack Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-5c98f5549b["{rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-5c98f5549b rook-ceph-crashcollector-ceph.cluster.openstack-5c98f5549b ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack["{rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack rook-ceph-crashcollector-ceph.cluster.openstack Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-67fb49ddb["{rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-67fb49ddb rook-ceph-crashcollector-ceph.cluster.openstack-67fb49ddb ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-67fb49ddb["{rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-67fb49ddb rook-ceph-crashcollector-ceph.cluster.openstack-67fb49ddb ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-67fb49ddb-p8ggn["{rook-ceph_rook-ceph-crashcollector-ceph_cluster_openstack-67fb49ddb-p8ggn rook-ceph-crashcollector-ceph.cluster.openstack-67fb49ddb-p8ggn Pod rook-ceph}"]
rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack["{rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack rook-ceph-crashcollector-controller.cluster.openstack Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack-7c5464475b["{rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack-7c5464475b rook-ceph-crashcollector-controller.cluster.openstack-7c5464475b ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack-7c5464475b["{rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack-7c5464475b rook-ceph-crashcollector-controller.cluster.openstack-7c5464475b ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack-7c54mllq4["{rook-ceph_rook-ceph-crashcollector-controller_cluster_openstack-7c54mllq4 rook-ceph-crashcollector-controller.cluster.openstack-7c54mllq4 Pod rook-ceph}"]
rook-ceph_rook-ceph-exporter-ceph_cluster_openstack["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack rook-ceph-exporter-ceph.cluster.openstack Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b rook-ceph-exporter-ceph.cluster.openstack-55f76f776b ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b rook-ceph-exporter-ceph.cluster.openstack-55f76f776b ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85 rook-ceph-exporter-ceph.cluster.openstack-55f76f776b-gsw85 Pod rook-ceph}"]
rook-ceph_rook-ceph-exporter-ceph_cluster_openstack["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack rook-ceph-exporter-ceph.cluster.openstack Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-797b5675bd["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-797b5675bd rook-ceph-exporter-ceph.cluster.openstack-797b5675bd ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-exporter-controller_cluster_openstack["{rook-ceph_rook-ceph-exporter-controller_cluster_openstack rook-ceph-exporter-controller.cluster.openstack Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc897448["{rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc897448 rook-ceph-exporter-controller.cluster.openstack-84fc897448 ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc897448["{rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc897448 rook-ceph-exporter-controller.cluster.openstack-84fc897448 ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg["{rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg rook-ceph-exporter-controller.cluster.openstack-84fc8974486ltmg Pod rook-ceph}"]
rook-ceph_rook-ceph-mds-myfs-a["{rook-ceph_rook-ceph-mds-myfs-a rook-ceph-mds-myfs-a Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mds-myfs-a-6b7459f5bb["{rook-ceph_rook-ceph-mds-myfs-a-6b7459f5bb rook-ceph-mds-myfs-a-6b7459f5bb ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-mds-myfs-a-6b7459f5bb["{rook-ceph_rook-ceph-mds-myfs-a-6b7459f5bb rook-ceph-mds-myfs-a-6b7459f5bb ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mds-myfs-a-6b7459f5bb-9z546["{rook-ceph_rook-ceph-mds-myfs-a-6b7459f5bb-9z546 rook-ceph-mds-myfs-a-6b7459f5bb-9z546 Pod rook-ceph}"]
rook-ceph_rook-ceph-mds-myfs-b["{rook-ceph_rook-ceph-mds-myfs-b rook-ceph-mds-myfs-b Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mds-myfs-b-69cbcc7fc8["{rook-ceph_rook-ceph-mds-myfs-b-69cbcc7fc8 rook-ceph-mds-myfs-b-69cbcc7fc8 ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-mds-myfs-b-69cbcc7fc8["{rook-ceph_rook-ceph-mds-myfs-b-69cbcc7fc8 rook-ceph-mds-myfs-b-69cbcc7fc8 ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mds-myfs-b-69cbcc7fc8-hvjqk["{rook-ceph_rook-ceph-mds-myfs-b-69cbcc7fc8-hvjqk rook-ceph-mds-myfs-b-69cbcc7fc8-hvjqk Pod rook-ceph}"]
rook-ceph_rook-ceph-mgr-a["{rook-ceph_rook-ceph-mgr-a rook-ceph-mgr-a Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mgr-a-6b69ffdfd["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd rook-ceph-mgr-a-6b69ffdfd ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-mgr-a-6b69ffdfd["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd rook-ceph-mgr-a-6b69ffdfd ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs rook-ceph-mgr-a-6b69ffdfd-tgcrs Pod rook-ceph}"]
rook-ceph_rook-ceph-mon-a["{rook-ceph_rook-ceph-mon-a rook-ceph-mon-a Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mon-a-888c947cd["{rook-ceph_rook-ceph-mon-a-888c947cd rook-ceph-mon-a-888c947cd ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-mon-a-888c947cd["{rook-ceph_rook-ceph-mon-a-888c947cd rook-ceph-mon-a-888c947cd ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-mon-a-888c947cd-fqwht["{rook-ceph_rook-ceph-mon-a-888c947cd-fqwht rook-ceph-mon-a-888c947cd-fqwht Pod rook-ceph}"]
rook-ceph_rook-ceph-operator["{rook-ceph_rook-ceph-operator rook-ceph-operator Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-operator-68f986dbd4["{rook-ceph_rook-ceph-operator-68f986dbd4 rook-ceph-operator-68f986dbd4 ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-operator-68f986dbd4["{rook-ceph_rook-ceph-operator-68f986dbd4 rook-ceph-operator-68f986dbd4 ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-operator-68f986dbd4-phr65["{rook-ceph_rook-ceph-operator-68f986dbd4-phr65 rook-ceph-operator-68f986dbd4-phr65 Pod rook-ceph}"]
rook-ceph_rook-ceph-operator["{rook-ceph_rook-ceph-operator rook-ceph-operator Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-operator-84bbd7db8c["{rook-ceph_rook-ceph-operator-84bbd7db8c rook-ceph-operator-84bbd7db8c ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-osd-0["{rook-ceph_rook-ceph-osd-0 rook-ceph-osd-0 Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-osd-0-5566dccbc["{rook-ceph_rook-ceph-osd-0-5566dccbc rook-ceph-osd-0-5566dccbc ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-osd-0-5566dccbc["{rook-ceph_rook-ceph-osd-0-5566dccbc rook-ceph-osd-0-5566dccbc ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-osd-0-5566dccbc-q9tdf["{rook-ceph_rook-ceph-osd-0-5566dccbc-q9tdf rook-ceph-osd-0-5566dccbc-q9tdf Pod rook-ceph}"]
rook-ceph_rook-ceph-osd-1["{rook-ceph_rook-ceph-osd-1 rook-ceph-osd-1 Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-osd-1-7f87b96d45["{rook-ceph_rook-ceph-osd-1-7f87b96d45 rook-ceph-osd-1-7f87b96d45 ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-osd-1-7f87b96d45["{rook-ceph_rook-ceph-osd-1-7f87b96d45 rook-ceph-osd-1-7f87b96d45 ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-osd-1-7f87b96d45-g6g2n["{rook-ceph_rook-ceph-osd-1-7f87b96d45-g6g2n rook-ceph-osd-1-7f87b96d45-g6g2n Pod rook-ceph}"]
rook-ceph_rook-ceph-osd-2["{rook-ceph_rook-ceph-osd-2 rook-ceph-osd-2 Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-osd-2-6454ff9dbb["{rook-ceph_rook-ceph-osd-2-6454ff9dbb rook-ceph-osd-2-6454ff9dbb ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-osd-2-6454ff9dbb["{rook-ceph_rook-ceph-osd-2-6454ff9dbb rook-ceph-osd-2-6454ff9dbb ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-osd-2-6454ff9dbb-4nrn2["{rook-ceph_rook-ceph-osd-2-6454ff9dbb-4nrn2 rook-ceph-osd-2-6454ff9dbb-4nrn2 Pod rook-ceph}"]
rook-ceph_rook-ceph-tools["{rook-ceph_rook-ceph-tools rook-ceph-tools Deployment rook-ceph}"] -->|owns| rook-ceph_rook-ceph-tools-5d5ff75c8f["{rook-ceph_rook-ceph-tools-5d5ff75c8f rook-ceph-tools-5d5ff75c8f ReplicaSet rook-ceph}"]
rook-ceph_rook-ceph-tools-5d5ff75c8f["{rook-ceph_rook-ceph-tools-5d5ff75c8f rook-ceph-tools-5d5ff75c8f ReplicaSet rook-ceph}"] -->|owns| rook-ceph_rook-ceph-tools-5d5ff75c8f-w78xs["{rook-ceph_rook-ceph-tools-5d5ff75c8f-w78xs rook-ceph-tools-5d5ff75c8f-w78xs Pod rook-ceph}"]
rook-ceph_rook-ceph-exporter["{rook-ceph_rook-ceph-exporter rook-ceph-exporter Service rook-ceph}"] -->|routes| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85 rook-ceph-exporter-ceph.cluster.openstack-55f76f776b-gsw85 Pod rook-ceph}"]
rook-ceph_rook-ceph-exporter["{rook-ceph_rook-ceph-exporter rook-ceph-exporter Service rook-ceph}"] -->|routes| rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg["{rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg rook-ceph-exporter-controller.cluster.openstack-84fc8974486ltmg Pod rook-ceph}"]
rook-ceph_rook-ceph-mgr["{rook-ceph_rook-ceph-mgr rook-ceph-mgr Service rook-ceph}"] -->|routes| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs rook-ceph-mgr-a-6b69ffdfd-tgcrs Pod rook-ceph}"]
rook-ceph_rook-ceph-mgr-dashboard["{rook-ceph_rook-ceph-mgr-dashboard rook-ceph-mgr-dashboard Service rook-ceph}"] -->|routes| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs rook-ceph-mgr-a-6b69ffdfd-tgcrs Pod rook-ceph}"]
rook-ceph_rook-ceph-exporter-dkzx2["{rook-ceph_rook-ceph-exporter-dkzx2 rook-ceph-exporter-dkzx2 EndpointSlice rook-ceph}"] -->|targets| rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg["{rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg rook-ceph-exporter-controller.cluster.openstack-84fc8974486ltmg Pod rook-ceph}"]
rook-ceph_rook-ceph-exporter-dkzx2["{rook-ceph_rook-ceph-exporter-dkzx2 rook-ceph-exporter-dkzx2 EndpointSlice rook-ceph}"] -->|targets| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85["{rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85 rook-ceph-exporter-ceph.cluster.openstack-55f76f776b-gsw85 Pod rook-ceph}"]
rook-ceph_rook-ceph-mgr-dashboard-q8k29["{rook-ceph_rook-ceph-mgr-dashboard-q8k29 rook-ceph-mgr-dashboard-q8k29 EndpointSlice rook-ceph}"] -->|targets| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs rook-ceph-mgr-a-6b69ffdfd-tgcrs Pod rook-ceph}"]
rook-ceph_rook-ceph-mgr-mkbqb["{rook-ceph_rook-ceph-mgr-mkbqb rook-ceph-mgr-mkbqb EndpointSlice rook-ceph}"] -->|targets| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["{rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs rook-ceph-mgr-a-6b69ffdfd-tgcrs Pod rook-ceph}"]
rook-ceph_csi-cephfsplugin["{rook-ceph_csi-cephfsplugin csi-cephfsplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-2k4cc["{rook-ceph_csi-cephfsplugin-2k4cc csi-cephfsplugin-2k4cc Pod rook-ceph}"]
rook-ceph_csi-cephfsplugin["{rook-ceph_csi-cephfsplugin csi-cephfsplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-64xq7["{rook-ceph_csi-cephfsplugin-64xq7 csi-cephfsplugin-64xq7 Pod rook-ceph}"]
rook-ceph_csi-cephfsplugin["{rook-ceph_csi-cephfsplugin csi-cephfsplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-kldff["{rook-ceph_csi-cephfsplugin-kldff csi-cephfsplugin-kldff Pod rook-ceph}"]
rook-ceph_csi-cephfsplugin["{rook-ceph_csi-cephfsplugin csi-cephfsplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-lzg42["{rook-ceph_csi-cephfsplugin-lzg42 csi-cephfsplugin-lzg42 Pod rook-ceph}"]
rook-ceph_csi-cephfsplugin["{rook-ceph_csi-cephfsplugin csi-cephfsplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-cephfsplugin-r69g9["{rook-ceph_csi-cephfsplugin-r69g9 csi-cephfsplugin-r69g9 Pod rook-ceph}"]
rook-ceph_csi-rbdplugin["{rook-ceph_csi-rbdplugin csi-rbdplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-7phlf["{rook-ceph_csi-rbdplugin-7phlf csi-rbdplugin-7phlf Pod rook-ceph}"]
rook-ceph_csi-rbdplugin["{rook-ceph_csi-rbdplugin csi-rbdplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-fgk75["{rook-ceph_csi-rbdplugin-fgk75 csi-rbdplugin-fgk75 Pod rook-ceph}"]
rook-ceph_csi-rbdplugin["{rook-ceph_csi-rbdplugin csi-rbdplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-j56b5["{rook-ceph_csi-rbdplugin-j56b5 csi-rbdplugin-j56b5 Pod rook-ceph}"]
rook-ceph_csi-rbdplugin["{rook-ceph_csi-rbdplugin csi-rbdplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-s24xr["{rook-ceph_csi-rbdplugin-s24xr csi-rbdplugin-s24xr Pod rook-ceph}"]
rook-ceph_csi-rbdplugin["{rook-ceph_csi-rbdplugin csi-rbdplugin DaemonSet rook-ceph}"] -->|owns| rook-ceph_csi-rbdplugin-xdm9j["{rook-ceph_csi-rbdplugin-xdm9j csi-rbdplugin-xdm9j Pod rook-ceph}"]
