graph LR
rook-ceph_rook-ceph-exporter["rook-ceph-exporter"] -->|routes| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85["rook-ceph-exporter-ceph.cluster.openstack-55f76f776b-gsw85"]
rook-ceph_rook-ceph-exporter["rook-ceph-exporter"] -->|routes| rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg["rook-ceph-exporter-controller.cluster.openstack-84fc8974486ltmg"]
rook-ceph_rook-ceph-mgr["rook-ceph-mgr"] -->|routes| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["rook-ceph-mgr-a-6b69ffdfd-tgcrs"]
rook-ceph_rook-ceph-mgr-dashboard["rook-ceph-mgr-dashboard"] -->|routes| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["rook-ceph-mgr-a-6b69ffdfd-tgcrs"]
openstack_metadata["metadata"] -->|routes| openstack_nova-metadata["nova-metadata"]
openstack_metadata["metadata"] -->|routes| openstack_nova-metadata["nova-metadata"]
openstack_metadata["metadata"] -->|routes| openstack_nova-metadata["nova-metadata"]
openstack_nova["nova"] -->|routes| openstack_nova-api["nova-api"]
openstack_nova["nova"] -->|routes| openstack_nova-api["nova-api"]
openstack_nova["nova"] -->|routes| openstack_nova-api["nova-api"]
openstack_novncproxy["novncproxy"] -->|routes| openstack_nova-novncproxy["nova-novncproxy"]
openstack_novncproxy["novncproxy"] -->|routes| openstack_nova-novncproxy["nova-novncproxy"]
openstack_novncproxy["novncproxy"] -->|routes| openstack_nova-novncproxy["nova-novncproxy"]
cert-manager_cert-manager-cainjector-pdx4j["cert-manager-cainjector-pdx4j"] -->|targets| cert-manager_cert-manager-cainjector-55d94dc4cc-85kjv["cert-manager-cainjector-55d94dc4cc-85kjv"]
cert-manager_cert-manager-vv9zc["cert-manager-vv9zc"] -->|targets| cert-manager_cert-manager-74b56b6655-5jfsc["cert-manager-74b56b6655-5jfsc"]
cert-manager_cert-manager-webhook-ng7d2["cert-manager-webhook-ng7d2"] -->|targets| cert-manager_cert-manager-webhook-564f647c66-8b55j["cert-manager-webhook-564f647c66-8b55j"]
default_kubernetes["kubernetes"] -->|targets| metallb-system_metallb-speaker-mphfw["metallb-speaker-mphfw"]
fluentbit_fluentbit-fluent-bit-nmldk["fluentbit-fluent-bit-nmldk"] -->|targets| fluentbit_fluentbit-fluent-bit-bnspb["fluentbit-fluent-bit-bnspb"]
fluentbit_fluentbit-fluent-bit-nmldk["fluentbit-fluent-bit-nmldk"] -->|targets| fluentbit_fluentbit-fluent-bit-kt78f["fluentbit-fluent-bit-kt78f"]
fluentbit_fluentbit-fluent-bit-nmldk["fluentbit-fluent-bit-nmldk"] -->|targets| fluentbit_fluentbit-fluent-bit-9j447["fluentbit-fluent-bit-9j447"]
fluentbit_fluentbit-fluent-bit-nmldk["fluentbit-fluent-bit-nmldk"] -->|targets| fluentbit_fluentbit-fluent-bit-29skf["fluentbit-fluent-bit-29skf"]
fluentbit_fluentbit-fluent-bit-nmldk["fluentbit-fluent-bit-nmldk"] -->|targets| fluentbit_fluentbit-fluent-bit-tzkwf["fluentbit-fluent-bit-tzkwf"]
kube-system_coredns-km4zc["coredns-km4zc"] -->|targets| kube-system_coredns-5ddb6c7994-2sd55["coredns-5ddb6c7994-2sd55"]
kube-system_coredns-km4zc["coredns-km4zc"] -->|targets| kube-system_coredns-5ddb6c7994-26w5v["coredns-5ddb6c7994-26w5v"]
kube-system_kube-ovn-cni-8tmmw["kube-ovn-cni-8tmmw"] -->|targets| kube-system_kube-ovn-cni-hcmc2["kube-ovn-cni-hcmc2"]
kube-system_kube-ovn-cni-8tmmw["kube-ovn-cni-8tmmw"] -->|targets| kube-system_kube-ovn-cni-kjccl["kube-ovn-cni-kjccl"]
kube-system_kube-ovn-cni-8tmmw["kube-ovn-cni-8tmmw"] -->|targets| kube-system_kube-ovn-cni-xpd8d["kube-ovn-cni-xpd8d"]
kube-system_kube-ovn-cni-8tmmw["kube-ovn-cni-8tmmw"] -->|targets| kube-system_kube-ovn-cni-f7dls["kube-ovn-cni-f7dls"]
kube-system_kube-ovn-cni-8tmmw["kube-ovn-cni-8tmmw"] -->|targets| kube-system_kube-ovn-cni-t54xl["kube-ovn-cni-t54xl"]
kube-system_kube-ovn-cni-8tmmw["kube-ovn-cni-8tmmw"] -->|targets| kube-system_kube-ovn-cni-b98zh["kube-ovn-cni-b98zh"]
kube-system_kube-ovn-controller-chz2g["kube-ovn-controller-chz2g"] -->|targets| kube-system_kube-ovn-controller-56ffd466d6-m6l4w["kube-ovn-controller-56ffd466d6-m6l4w"]
kube-system_kube-ovn-monitor-qjn5q["kube-ovn-monitor-qjn5q"] -->|targets| kube-system_kube-ovn-monitor-7b75cf6675-qt8tc["kube-ovn-monitor-7b75cf6675-qt8tc"]
kube-system_kube-ovn-pinger-8m4rz["kube-ovn-pinger-8m4rz"] -->|targets| kube-system_kube-ovn-pinger-zhwhd["kube-ovn-pinger-zhwhd"]
kube-system_kube-ovn-pinger-8m4rz["kube-ovn-pinger-8m4rz"] -->|targets| kube-system_kube-ovn-pinger-cmlbm["kube-ovn-pinger-cmlbm"]
kube-system_kube-ovn-pinger-8m4rz["kube-ovn-pinger-8m4rz"] -->|targets| kube-system_kube-ovn-pinger-kgnqx["kube-ovn-pinger-kgnqx"]
kube-system_kube-ovn-pinger-8m4rz["kube-ovn-pinger-8m4rz"] -->|targets| kube-system_kube-ovn-pinger-g5g6f["kube-ovn-pinger-g5g6f"]
kube-system_kube-ovn-pinger-8m4rz["kube-ovn-pinger-8m4rz"] -->|targets| kube-system_kube-ovn-pinger-vtt79["kube-ovn-pinger-vtt79"]
kube-system_ovn-nb-t8mg7["ovn-nb-t8mg7"] -->|targets| kube-system_ovn-central-6989cd88bd-fkn8w["ovn-central-6989cd88bd-fkn8w"]
kube-system_ovn-northd-fclq7["ovn-northd-fclq7"] -->|targets| kube-system_ovn-central-6989cd88bd-fkn8w["ovn-central-6989cd88bd-fkn8w"]
kube-system_ovn-sb-df8nf["ovn-sb-df8nf"] -->|targets| kube-system_ovn-central-6989cd88bd-fkn8w["ovn-central-6989cd88bd-fkn8w"]
kubesphere-system_extensions-museum-ggw75["extensions-museum-ggw75"] -->|targets| kubesphere-system_extensions-museum-b5f957cc9-wm9nk["extensions-museum-b5f957cc9-wm9nk"]
kubesphere-system_ks-apiserver-wscvt["ks-apiserver-wscvt"] -->|targets| kubesphere-system_ks-apiserver-8bc56b888-ng26w["ks-apiserver-8bc56b888-ng26w"]
kubesphere-system_ks-console-kl85s["ks-console-kl85s"] -->|targets| kubesphere-system_ks-console-644d4d4d4d-t9qcq["ks-console-644d4d4d4d-t9qcq"]
kubesphere-system_ks-controller-manager-bvqxp["ks-controller-manager-bvqxp"] -->|targets| kubesphere-system_ks-controller-manager-5cdd475c84-kf9qn["ks-controller-manager-5cdd475c84-kf9qn"]
logging-tracing_jaeger-knfl4["jaeger-knfl4"] -->|targets| logging-tracing_jaeger-58d497df44-6zt8q["jaeger-58d497df44-6zt8q"]
logging-tracing_opensearch-cluster-master-ffgrj["opensearch-cluster-master-ffgrj"] -->|targets| logging-tracing_opensearch-cluster-master-0["opensearch-cluster-master-0"]
logging-tracing_opensearch-cluster-master-headless-5gsh6["opensearch-cluster-master-headless-5gsh6"] -->|targets| logging-tracing_opensearch-cluster-master-0["opensearch-cluster-master-0"]
mariadb-system_mariadb-operator-webhook-jvqpx["mariadb-operator-webhook-jvqpx"] -->|targets| mariadb-system_mariadb-operator-webhook-7786978598-tf24q["mariadb-operator-webhook-7786978598-tf24q"]
metallb-system_metallb-webhook-service-xr6nw["metallb-webhook-service-xr6nw"] -->|targets| metallb-system_metallb-controller-777b99b66c-kshg7["metallb-controller-777b99b66c-kshg7"]
nginx-gateway_nginx-gateway-fabric-k78m7["nginx-gateway-fabric-k78m7"] -->|targets| nginx-gateway_nginx-gateway-fabric-6b474b7869-vnfkj["nginx-gateway-fabric-6b474b7869-vnfkj"]
openstack_barbican-api-xp7jf["barbican-api-xp7jf"] -->|targets| openstack_barbican-api-57654c74f6-9d5nh["barbican-api-57654c74f6-9d5nh"]
openstack_cinder-api-v2qzp["cinder-api-v2qzp"] -->|targets| openstack_cinder-api-8b8b9965b-6d952["cinder-api-8b8b9965b-6d952"]
openstack_glance-api-txh2r["glance-api-txh2r"] -->|targets| openstack_glance-api-548876b7f8-hjg4c["glance-api-548876b7f8-hjg4c"]
openstack_heat-api-v5glh["heat-api-v5glh"] -->|targets| openstack_heat-api-588b946fd5-854b4["heat-api-588b946fd5-854b4"]
openstack_heat-cfn-6z94f["heat-cfn-6z94f"] -->|targets| openstack_heat-cfn-7b8cb9bc45-54c8n["heat-cfn-7b8cb9bc45-54c8n"]
openstack_horizon-int-2797s["horizon-int-2797s"] -->|targets| openstack_horizon-74f9bcf99c-8c4n9["horizon-74f9bcf99c-8c4n9"]
openstack_keystone-api-9vkbl["keystone-api-9vkbl"] -->|targets| openstack_keystone-api-6d6dbdf48-r82b2["keystone-api-6d6dbdf48-r82b2"]
openstack_mariadb-cluster-7xpm2["mariadb-cluster-7xpm2"] -->|targets| openstack_mariadb-cluster-0["mariadb-cluster-0"]
openstack_mariadb-cluster-internal-zfgcq["mariadb-cluster-internal-zfgcq"] -->|targets| openstack_mariadb-cluster-0["mariadb-cluster-0"]
openstack_mariadb-zh7lh["mariadb-zh7lh"] -->|targets| openstack_mariadb-cluster-0["mariadb-cluster-0"]
openstack_memcached-j7j7j["memcached-j7j7j"] -->|targets| openstack_memcached-0["memcached-0"]
openstack_neutron-server-wf9rq["neutron-server-wf9rq"] -->|targets| openstack_neutron-server-55f6864dc9-vv876["neutron-server-55f6864dc9-vv876"]
openstack_nova-api-2j88l["nova-api-2j88l"] -->|targets| openstack_nova-api-osapi-6cf558756b-7gfw8["nova-api-osapi-6cf558756b-7gfw8"]
openstack_nova-metadata-tkcbz["nova-metadata-tkcbz"] -->|targets| openstack_nova-api-metadata-b5bdffb95-q92gm["nova-api-metadata-b5bdffb95-q92gm"]
openstack_nova-novncproxy-rbzqs["nova-novncproxy-rbzqs"] -->|targets| openstack_nova-novncproxy-5bfbdbc6cb-n4jh8["nova-novncproxy-5bfbdbc6cb-n4jh8"]
openstack_octavia-api-kn8xj["octavia-api-kn8xj"] -->|targets| openstack_octavia-api-6f94c7d5df-fdvsm["octavia-api-6f94c7d5df-fdvsm"]
openstack_otlp-collector-nodeport-mctsc["otlp-collector-nodeport-mctsc"] -->|targets| openstack_otlp-opentelemetry-collector-8497bdff99-q9sxc["otlp-opentelemetry-collector-8497bdff99-q9sxc"]
openstack_otlp-opentelemetry-collector-k4xh4["otlp-opentelemetry-collector-k4xh4"] -->|targets| openstack_otlp-opentelemetry-collector-8497bdff99-q9sxc["otlp-opentelemetry-collector-8497bdff99-q9sxc"]
openstack_placement-api-8jmjs["placement-api-8jmjs"] -->|targets| openstack_placement-api-884f644c6-ztj6k["placement-api-884f644c6-ztj6k"]
openstack_rabbitmq-hjnv6["rabbitmq-hjnv6"] -->|targets| openstack_rabbitmq-server-0["rabbitmq-server-0"]
openstack_rabbitmq-nodes-5j9lf["rabbitmq-nodes-5j9lf"] -->|targets| openstack_rabbitmq-server-0["rabbitmq-server-0"]
rabbitmq-system_webhook-service-fzzpw["webhook-service-fzzpw"] -->|targets| rabbitmq-system_messaging-topology-operator-6dfc468844-cnq8v["messaging-topology-operator-6dfc468844-cnq8v"]
rook-ceph_rook-ceph-exporter-dkzx2["rook-ceph-exporter-dkzx2"] -->|targets| rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg["rook-ceph-exporter-controller.cluster.openstack-84fc8974486ltmg"]
rook-ceph_rook-ceph-exporter-dkzx2["rook-ceph-exporter-dkzx2"] -->|targets| rook-ceph_rook-ceph-exporter-ceph_cluster_openstack-55f76f776b-gsw85["rook-ceph-exporter-ceph.cluster.openstack-55f76f776b-gsw85"]
rook-ceph_rook-ceph-mgr-dashboard-q8k29["rook-ceph-mgr-dashboard-q8k29"] -->|targets| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["rook-ceph-mgr-a-6b69ffdfd-tgcrs"]
rook-ceph_rook-ceph-mgr-mkbqb["rook-ceph-mgr-mkbqb"] -->|targets| rook-ceph_rook-ceph-mgr-a-6b69ffdfd-tgcrs["rook-ceph-mgr-a-6b69ffdfd-tgcrs"]
logging-tracing_opensearch-cluster-master-opensearch-cluster-master-0["opensearch-cluster-master-opensearch-cluster-master-0"] -->|binds| _pvc-3c060777-df58-4a19-aaf4-2bd0117fcbaa["pvc-3c060777-df58-4a19-aaf4-2bd0117fcbaa"]
_pvc-3c060777-df58-4a19-aaf4-2bd0117fcbaa["pvc-3c060777-df58-4a19-aaf4-2bd0117fcbaa"] -->|uses| _general["general"]
openstack_data-memcached-0["data-memcached-0"] -->|binds| _pvc-76b3d02a-3e9e-46fe-81b3-75a3576fe4d7["pvc-76b3d02a-3e9e-46fe-81b3-75a3576fe4d7"]
_pvc-76b3d02a-3e9e-46fe-81b3-75a3576fe4d7["pvc-76b3d02a-3e9e-46fe-81b3-75a3576fe4d7"] -->|uses| _general["general"]
openstack_glance-images["glance-images"] -->|binds| _pvc-412afb72-373a-4273-8d15-a7bf3a34daa4["pvc-412afb72-373a-4273-8d15-a7bf3a34daa4"]
_pvc-412afb72-373a-4273-8d15-a7bf3a34daa4["pvc-412afb72-373a-4273-8d15-a7bf3a34daa4"] -->|uses| _general-multi-attach["general-multi-attach"]
openstack_mariadb-backup["mariadb-backup"] -->|binds| _pvc-aae762a7-3e63-4a70-96af-fd5d78e67d07["pvc-aae762a7-3e63-4a70-96af-fd5d78e67d07"]
_pvc-aae762a7-3e63-4a70-96af-fd5d78e67d07["pvc-aae762a7-3e63-4a70-96af-fd5d78e67d07"] -->|uses| _general["general"]
openstack_persistence-rabbitmq-server-0["persistence-rabbitmq-server-0"] -->|binds| _pvc-8651db59-b983-4a4f-9569-4df5188e003b["pvc-8651db59-b983-4a4f-9569-4df5188e003b"]
_pvc-8651db59-b983-4a4f-9569-4df5188e003b["pvc-8651db59-b983-4a4f-9569-4df5188e003b"] -->|uses| _general["general"]
openstack_storage-mariadb-cluster-0["storage-mariadb-cluster-0"] -->|binds| _pvc-3ce0f436-3611-4cdc-a98e-1dd786bbd4d7["pvc-3ce0f436-3611-4cdc-a98e-1dd786bbd4d7"]
_pvc-3ce0f436-3611-4cdc-a98e-1dd786bbd4d7["pvc-3ce0f436-3611-4cdc-a98e-1dd786bbd4d7"] -->|uses| _general["general"]
kube-system_kube-ovn-controller-56ffd466d6-m6l4w["kube-ovn-controller-56ffd466d6-m6l4w"] -->|allow| openstack_memcached-0["memcached-0"]
kube-system_kube-proxy-z2psp["kube-proxy-z2psp"] -->|allow| openstack_memcached-0["memcached-0"]
openstack_ceilometer-ks-user-zmmrd["ceilometer-ks-user-zmmrd"] -->|allow| openstack_memcached-0["memcached-0"]
openstack_nova-compute-default-pg56v["nova-compute-default-pg56v"] -->|allow| openstack_memcached-0["memcached-0"]
rook-ceph_rook-ceph-exporter-controller_cluster_openstack-84fc8974486ltmg["rook-ceph-exporter-controller.cluster.openstack-84fc8974486ltmg"] -->|allow| openstack_memcached-0["memcached-0"]
rook-ceph_rook-ceph-osd-0-5566dccbc-q9tdf["rook-ceph-osd-0-5566dccbc-q9tdf"] -->|allow| openstack_memcached-0["memcached-0"]
openstack_cinder-volume-usage-audit-29118725-4njsh["cinder-volume-usage-audit-29118725-4njsh"] -->|allow| openstack_memcached-0["memcached-0"]
