apiVersion: v1
data:
  relay: |
    exporters:
      debug: {}
      prometheus:
        add_metric_suffixes: false
        endpoint: ${env:MY_POD_IP}:8889
        namespace: otlp
        resource_to_telemetry_conversion:
          enabled: true

      otlp:
        endpoint: "jaeger.logging-tracing.svc.cluster.openstack:4317"
        tls:
          insecure: true

      elasticsearch:
        endpoints:
        - "http://opensearch-cluster-master.logging-tracing.svc.cluster.openstack:9200"
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      pipelines:
        metrics:
          exporters:
          - prometheus
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        traces:
          receivers:
          - otlp
          processors:
          - memory_limiter
          - batch
          exporters:
          - otlp
          - elasticsearch
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: otlp
    meta.helm.sh/release-namespace: openstack
  creationTimestamp: "2025-04-19T15:46:44Z"
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: otlp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.122.1
    helm.sh/chart: opentelemetry-collector-0.120.2
  name: otlp-opentelemetry-collector
  namespace: openstack
  resourceVersion: "4016010"
  uid: b196bb90-55cb-4f24-94b2-787304d13618
